name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION: us-central1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          export_default_credentials: true

      - name: Build & Submit Container
        run: |
          gcloud builds submit  --gcs-log-dir=gs://perimeter-logs --verbosity=debug \
            --tag gcr.io/${{ env.GCP_PROJECT }}/telegrambot

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy telegrambot \
            --project=${{ env.GCP_PROJECT }} \
            --image gcr.io/${{ env.GCP_PROJECT }}/telegrambot \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars GCP_PROJECT=${{ env.GCP_PROJECT }} \
            --set-secrets BOT_TOKEN=telegram-bot-token:latest
